cures-hub/cures-condec-jira

pom.xml
src/main/resources/atlassian-plugin.xml
src/main/resources/js/jquery/jquery.contextMenu.js
src/main/resources/js/jquery/jquery.js
src/main/resources/js/jstree/jstree.js
src/main/resources/js/management.js
src/main/resources/js/view.context.menu.js
src/main/resources/js/view.decision.knowledge.page.js
src/main/resources/js/view.issue.module.js
src/main/resources/js/view.tab.panel.js
src/main/resources/js/view.treant.js
src/main/resources/js/view.tree.viewer.js
src/main/resources/templates/decisionKnowledgePage.vm
src/main/resources/templates/issueModule.vm
src/main/resources/templates/tabPanel.vm

Hi @kleebaum, @dekome and @Jcl15,
with this branch the add-on does not break Jira issue functions any more when an issue is accessed with pre-selected decision knowledge tab (ex. http://jira-se.ifi.uni-heidelberg.de/browse/CONDEC-293?page=de.uhd.ifi.se.decision.management.jira:condec-tab-panel) and the tree view (treant) seems to function too.
Please check the code and read my commit messages. We should probably create extra refactoring work items in our project for javascript.
Best regards,
Lukasz

Condec 293.j query conflicts fix

---

src/main/resources/atlassian-plugin.xml
src/main/resources/js/management.js
src/main/resources/js/view.context.menu.js
src/main/resources/js/view.decision.knowledge.page.js
src/main/resources/js/view.issue.module.js
src/main/resources/js/view.tab.panel.js
src/main/resources/js/view.treant.js
src/main/resources/js/view.tree.viewer.js
src/main/resources/templates/decisionKnowledgePage.vm
src/main/resources/templates/issueModule.vm
src/main/resources/templates/tabPanel.vm

[goal] Provide different updateView() methods on every workspace, e.g. on the JIRA issue view and the decision knowledge page. [/goal]
[decision] Provide a different Javascript web resource containing the respective updateView() method in each velocity template file.
For example, in the template file "issueModule.vm" the following resource is included:
`$webResourceManager.requireResource("de.uhd.ifi.se.decision.management.jira:issue-module-resources")`
In the atlassian-plugin.xml this resource only contains the "view.issue.module.js" file:
`	<web-resource key="issue-module-resources"
name="ConDec Java Script Resources for the Issue Module">
<description>
Provides the Java Script file used in the issue module.
</description>
<context>jira.view.issue</context>
<resource type="download" …

ConDec-53: Restore updateView() method and reorganise atlassian-plugin.xml

---

src/main/resources/atlassian-plugin.xml
src/main/resources/js/jstree/jstree.js
src/main/resources/js/view.context.menu.js
src/main/resources/js/view.issue.module.js
src/main/resources/js/view.tab.panel.js
src/main/resources/js/view.tree.viewer.js
src/main/resources/templates/decisionKnowledgePage.vm

If we don't provide this context (or even the context atl.general) some methods (e.g. buildTreant) cannot be found in the JIRA issue view.

ConDec-53: Add jira.view.issue context to decision knowledge management resources

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/view/DecisionKnowledgeReport.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/treant/Node.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/treant/Treant.java
src/main/java/de/uhd/ifi/se/decision/management/jira/webhook/WebhookContentProvider.java
src/main/resources/js/view.context.menu.js
src/main/resources/js/view.decision.knowledge.page.js
src/main/resources/js/view.issue.module.js
src/main/resources/js/view.treant.js
src/test/java/de/uhd/ifi/se/decision/management/jira/view/treant/TestNode.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/treant/TestTreant.java

[issue]How to link to respective JIRA issues from Treant nodes?[/issue]
[decision]Use the context menu to provide the link to the JIRA issue and only keep hyperlinks on nodes in the webhook since there is no context menu.[/decision]
[pro]Prevents the user from accidentally clicking the link, improves usability[/pro]

ConDec-295: Move hyperlinks from Treant nodes to context menu (except for webhook)

---

.gitignore
src/main/java/de/uhd/ifi/se/decision/management/jira/model/Graph.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/GraphImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/KnowledgeRest.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ViewRest.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/GraphFiltering.java
src/main/resources/js/rest.client.js

… match a Query including Sentences
Sentences can only be filtered by their creation Date. Other Filters don't affect the resulting Sentences returned by the function

ConDec-314: Provide REST method that allows to get all elements, that match a query including sentences from isse comments

---

src/main/resources/atlassian-plugin.xml
src/main/resources/css/condec.css
src/main/resources/js/rest.client.js
src/main/resources/js/view.issue.module.js
src/main/resources/templates/dialog.vm

ConDec-279:Add Export as Table, custom filters not working yet

---

src/main/resources/js/view.issue.module.js
src/main/resources/templates/dialog.vm

Small fix to handle different formed urls

CONDEC-354: Fix url path on production system for export as table

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/DecXtractEventListener.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/model/impl/CommentImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/persistence/ActiveObjectsManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ConfigRest.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/TestDecXtractEventListener.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/persistence/TestActiveObjectsManager.java

Added Event Listener to DecXtract

ConDec-373: Event listener for comments that triggers classification and extraction of decision knowledge in JIRA issue comments

---

src/main/resources/js/view.issue.module.js
src/main/resources/templates/dialog.vm

Change structure from Pure array to Object with metainformation and array

CONDEC-376: Change structure of how Json gets printed to file

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/DecXtractEventListener.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/model/impl/CommentImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/model/impl/SentenceImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/model/util/CommentSplitter.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/persistence/ActiveObjectsManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/view/macros/AlternativeMacro.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/view/macros/ConMacro.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/view/macros/DecisionMacro.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/view/macros/IssueMacro.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/view/macros/ProMacro.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/DecisionKnowledgeElementImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/KnowledgeType.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/KnowledgeRest.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/treant/Node.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/treeviewer/Data.java
src/main/resources/atlassian-plugin.xml
src/main/resources/js/view.commentTab.toolbar-init.js
src/main/resources/templates/settingsForSingleProject.vm
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/model/TestComment.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/persistence/TestActiveObjectsManager.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/view/TestMacro.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/knowledgerest/TestEditSentenceBody.java

Switch from [tags] to {tags}
Still work in progress to see codacy issues

ConDec-375: Change tags in issue comments to JIRA like tags

---

src/main/resources/js/condec.api.js
src/main/resources/templates/decisionKnowledgePage.vm
src/main/resources/templates/issueModule.vm
src/main/resources/templates/tabPanel.vm

- conDecAPI.checkIfProjectKeyIsValid() method tries to get the project key in case it could not be received during the construction of the conDecAPI object
- Add references to the conDecAPI.checkIfProjectKeyIsValid() in the velocity template files
- Add more look and feel like JIRA to tab panel search field

ConDec-422: Add conDecAPI.checkIfProjectKeyIsValid() 

---

src/main/java/de/uhd/ifi/se/decision/management/jira/rest/KnowledgeRest.java
src/main/resources/js/condec.api.js
src/main/resources/js/condec.jira.issue.module.js
src/main/resources/templates/dialog.vm

Implement new Rest Function to export multiple Lists with DecisionElements

Condec 450

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/CodeSummarizer.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/GitClient.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/SummarizationEventListener.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/impl/CodeSummarizerImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/impl/GitClientImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/quality/CommentMetricCalculator.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/KnowledgeRest.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/codesummarizer/TestCodeSummarizer.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/gitclient/TestGetCommitsForJiraIssue.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/gitclient/TestGetDiff.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/gitclient/TestGetNumberOfCommits.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/gitclient/TestSetUpGit.java

Please consider this tiny refactoring branch. I would like to prevent applying these changes later in my feature branch(es) for decision knowledge extraction from git/files.

ConDec-465: Refactor.git client.method.signatures

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/GitRepositoryFSManager.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/TestGitRepositoryFSManager.java

Here is the git repository file system manager our gitClient implementation should use in the future for multi-user/multi-request operation of our plugin.
After this branch the gitClientImpl should be adjusted or an alternative implementation could be used.

ConDec-498: Manage file system directories for branches of git repositories

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/impl/GitClientImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/GitDecXtract.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ViewRest.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/diffviewer/BranchDiff.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/diffviewer/DiffViewer.java
src/test/java/de/uhd/ifi/se/decision/management/jira/TestSetUpWithIssues.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/TestGitDecXtract.java
src/test/java/de/uhd/ifi/se/decision/management/jira/mocks/MockIssueManagerSelfImpl.java
src/test/java/de/uhd/ifi/se/decision/management/jira/mocks/MockPluginSettings.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/viewrest/TestElementsFromBranchesOfJiraIssue.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/diffviewer/TestBranchDiff.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/diffviewer/TestDiffViewer.java

Hi @kleebaum and @dekome ,
here is a tiny branch introducing new rest api method.
Please note the rationale documented in commit's 0fe070c message. I have deliberately picked the wrong alternative as decision, which should not be picked as one.
EDIT: tests added for new classes

Condec 503.rest.api.feature.branch.rationale

---

src/main/java/de/uhd/ifi/se/decision/management/jira/config/JiraIssueTypeGenerator.java
src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/FilterExtractor.java
src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/FilterSettings.java
src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/impl/FilterSettingsImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/JiraIssuePersistenceManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ViewRest.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/vis/VisDataProvider.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/vis/VisGraph.java
src/test/java/de/uhd/ifi/se/decision/management/jira/config/TestJiraIssueTypeGenerator.java
src/test/java/de/uhd/ifi/se/decision/management/jira/config/TestPluginInitializer.java
src/test/java/de/uhd/ifi/se/decision/management/jira/mocks/MockIssueTypeSchemeManager.java
src/test/java/de/uhd/ifi/se/decision/management/jira/model/TestDecisionKnowledgeElementTypeString.java
src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/jiraissuepersistencemanager/TestGetUnlinkedElements.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/viewrest/TestGetVis.java
src/test/java/de/uhd/ifi/se/decision/management/jira/testdata/JiraIssues.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/vis/TestVisGraph.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/vis/TestVisGraphNode.java

Filter in issue module is not working like intended. The documentation location and issue type 
filter is not filtering the graph. 
Goal: Fix Filter, shorten the code and reuse the filter from the evolution views

ConDec-529: Fix Issue module filter

---

src/main/resources/atlassian-plugin.xml
src/main/resources/i18n/condec.properties
src/main/resources/i18n/condec_de_DE.properties
src/main/resources/js/condec.api.js
src/main/resources/js/condec.dialog.js
src/main/resources/js/condec.release.note.page.js
src/main/resources/templates/dialogs/createReleaseNoteDialog.vm
src/main/resources/templates/releaseNotePage.vm

ConDec-556: Add frontend functionality to create release notes
add new page for Release notes
add button to create a new release note
open dialog with filled fields to configurate release note

ConDec-556: Add frontend functionality to create release notes

---

src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNoteIssueProposal.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/impl/ReleaseNoteIssueProposalImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ReleaseNoteRest.java
src/main/resources/templates/dialogs/createReleaseNoteDialog.vm
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestReleaseNoteIssueProposal.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/releasenotes/TestGetProposedIssues.java
src/test/java/de/uhd/ifi/se/decision/management/jira/testdata/JiraIssues.java

ConDec-559: add rest end point for release-notes:
Add Rest Resource for Release-Note Generation
First implementation of Proposal Rating
Extend Proposal Class to work with Rating System

ConDec-559: add rest resource for release-note generation

---

src/main/resources/atlassian-plugin.xml
src/main/resources/css/condec.css
src/main/resources/js/condec.api.js
src/main/resources/js/condec.dialog.js

ConDec-570: display proposed issues for release notes
make post request with selected release note issues

ConDec-570: display proposed issues for release notes

---

src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ReleaseNoteRest.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/releasenotes/TestGetProposedIssues.java

change from graph.getAllGraphs() graph.getAllElementsatchingQuery()

ConDec--575: increase speed of releaseNote calls

---

src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/ReleaseNotesPersistenceManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/AdditionalConfigurationOptions.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNote.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNoteConfiguration.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TargetGroup.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/impl/ReleaseNoteConfigurationImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/impl/ReleaseNoteImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ReleaseNoteRest.java
src/main/resources/js/condec.api.js
src/main/resources/js/condec.dialog.js
src/main/resources/js/condec.release.note.page.js
src/main/resources/templates/dialogs/createReleaseNoteDialog.vm
src/main/resources/templates/releaseNotePage.vm
src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/releasenotesreleasemanager/TestReleaseNotesPersistenceManager.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/AdditionalConfigurationOptionsTest.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestReleaseNote.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestTargetGroup.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/releasenotes/TestCRUDReleaseNotes.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/releasenotes/TestGetProposedIssues.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/releasenotes/TestPostProposedKeys.java

ConDec-579:
Add additional configuration options to the creation of release notes
- remove stakeholder
- changing targetgroup or softwaretype results in other selections
- add decision knowledge
- add search

ConDec-579: Add additional configuration options

---

src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ReleaseNoteRest.java
src/main/resources/atlassian-plugin.xml

ConDec 571: Implement median interval rating system

ConDec 571: Implement median interval rating system

---

src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/ReleaseNotesPersistenceManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ReleaseNoteRest.java
src/main/resources/css/condec.css
src/main/resources/js/condec.api.js
src/main/resources/js/condec.dialog.js
src/main/resources/js/condec.release.note.page.js

ConDec-581: Improve exception handling release notes
-fix sql bug on production system
-add icons to decision knowledge elements

ConDec-581: Improve exception handling release notes

---

src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/AdditionalConfigurationOptions.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ReleaseNoteRest.java
src/main/resources/js/condec.dialog.js
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/AdditionalConfigurationOptionsTest.java

empty input fields completly before filling them again

ConDec-537: empty input fields completly before filling them again

---

src/main/resources/js/condec.dialog.js

fix release-note download as word

ConDec-591: fix release-note download as word

---

src/main/resources/js/condec.api.js
src/main/resources/js/condec.dialog.js

fix open create release-note dialog even when no releases exist

ConDec-592: fix open create release-note dialog without releases

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/GitDecXtract.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/GitDiffedCodeExtractionManager.java
src/main/resources/css/gitdiffviewer.css
src/main/resources/js/dashboard/condec.git.branches.dashboard.js
src/main/resources/js/dashboard/condec.report.js
src/test/java/de/uhd/ifi/se/decision/management/jira/view/TestFeatureBranchQualityDashboardItem.java

After https://github.com/cures-hub/cures-condec-jira/pull/203 is approved, rebase this branch onto dev.

ConDec-534: Improve dashboard UI

---

src/main/resources/templates/settings/settingsForSingleProject.vm
src/test/java/de/uhd/ifi/se/decision/management/jira/classification/TestClassificationTrainer.java
src/test/resources/classifier/defaultTrainingData.arff

Minor fixes for the classification module.
- Unit test training file location changed to test/resources/classification
- Selection of training file in settings for single project fixed

ConDec-561: Classification bug fixes

---

src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/AdditionalConfigurationOptions.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/JiraIssueMetric.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/MarkdownCreator.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/RatingCalculator.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNote.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNoteCategory.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNoteConfiguration.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNoteIssueProposal.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNotesCreator.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TargetGroup.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/impl/ReleaseNoteConfigurationImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/impl/ReleaseNoteImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/impl/ReleaseNoteIssueProposalImpl.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ReleaseNoteRest.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/AdditionalConfigurationOptionsTest.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestJiraIssueMetric.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestReleaseNote.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestReleaseNoteCategory.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestReleaseNoteConfiguration.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestReleaseNoteIssueProposal.java
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestTargetGroup.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/releasenotes/TestCRUDReleaseNotes.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/releasenotes/TestGetProposedIssues.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/releasenotes/TestPostProposedKeys.java

* Use List instead of ArrayList: Implement against interfaces, not classes
* Format release notes code with current format options

CONDEC-614: Refactor release notes management

---

src/main/resources/js/condec.api.js
src/main/resources/templates/settings/classificationSettings.vm

Condec 634.make.rest.calls.in.classifier.config.asynchronous

---

src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ViewRest.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/treant/Treant.java
src/main/java/de/uhd/ifi/se/decision/management/jira/webhook/WebhookContentProviderForTreant.java
src/main/resources/js/condec.api.js
src/main/resources/js/condec.jira.issue.module.js
src/main/resources/js/condec.knowledge.page.js
src/main/resources/js/condec.treant.js
src/main/resources/templates/jiraIssueModule.vm
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/viewrest/TestGetTreant.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/treant/TestTreant.java

CONDEC-701: Show all linked Elements in Tree Visualization View

---

src/main/resources/atlassian-plugin.xml
src/main/resources/js/condec.api.js
src/main/resources/js/condec.decision.table.js
src/main/resources/js/condec.jira.issue.module.js
src/main/resources/templates/jiraIssueModule.vm

In this pull request the visualisation of decision table with dummy data, is implemented.

CONDEC-700: Create Decision Table View

---

src/main/java/de/uhd/ifi/se/decision/management/jira/consistency/ContextInformation.java
src/main/java/de/uhd/ifi/se/decision/management/jira/consistency/DuplicateDetectionManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/consistency/implementation/TimeCIP.java
src/main/resources/js/condec.dialog.js
src/main/resources/js/condec.jira.issue.module.consistency.js
src/main/resources/js/condec.jira.issue.module.js

Fixed reload bug in Decision Knowledge Tabs
Fixed Time-Filter Bug in Graph View
Fixed Bug when linking Issues from Related and Duplicate Tab

Condec 705.bug.fixing.after.systemtests.for.duplicate.and.link.detection

---

src/main/resources/js/condec.decision.table.js

In this pull request, the possibility was added to create, read, update and delete alternatives and solutions in the decision table.

CONDEC-700: Add possibility to manage alternatives and solutions

---

src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/FilteringManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ViewRest.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/decisiontable/DecisionTable.java
src/main/resources/js/condec.api.js
src/main/resources/js/condec.decision.table.js
src/main/resources/js/condec.dialog.js
src/main/resources/js/condec.jira.issue.module.js
src/main/resources/templates/dialogs/editDecisionTableCriterionDialog.vm
src/main/resources/templates/jiraIssueModule.vm
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/viewrest/TestGetDecisionTable.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/decisiontable/TestDecisionTable.java

Add filter function for link distance for a given root knowledge element in FilteringManager

CONDEC-700: Add link distance filter to filter manager

---

src/main/java/de/uhd/ifi/se/decision/management/jira/view/decisiontable/Alternative.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/decisiontable/Argument.java
src/main/java/de/uhd/ifi/se/decision/management/jira/view/decisiontable/Criterion.java
src/main/resources/js/condec.api.js
src/main/resources/js/condec.decision.table.js
src/main/resources/js/condec.dialog.js
src/main/resources/js/condec.jira.issue.module.js
src/main/resources/templates/jiraIssueModule.vm
src/test/java/de/uhd/ifi/se/decision/management/jira/view/decisiontable/TestAlternative.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/decisiontable/TestArgument.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/decisiontable/TestCriterion.java

Improve usability of decision table by adding icons to solution options and argument. This has been done to improve the recognition of different Knowledge Element Types like Alternative/Decision and Pro-Argument/Con-Argument.

CONDEC-700: Improve usability of decision table 

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/CodeFileExtractorAndMaintainer.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/GitClientForSingleRepository.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/git/ChangedFile.java
src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/singlelocations/CodeClassPersistenceManager.java
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/TestCodeFileExtractorAndMaintainer.java
src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/codeclasspersistencemanager/TestDeleteKnowledgeElement.java
src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/codeclasspersistencemanager/TestDeleteKnowledgeElements.java
src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/codeclasspersistencemanager/TestGetCreator.java
src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/codeclasspersistencemanager/TestInsertKnowledgeElement.java
src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/codeclasspersistencemanager/TestUpdateKnowledgeElement.java

responsible for extraction of code files and linking when cloning the repo and for maintaining links on git fetch

CONDEC-822: Add CodeFileExtractorAndMaintainer class 

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/CodeSummarizer.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/CodeFileExtractorAndMaintainer.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/GitClientForSingleRepository.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/git/ChangedFile.java
src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/ConfigPersistenceManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ConfigRest.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/configrest/TestDeleteGitRepos.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/configrest/TestSetDecisionTableCriteriaQuery.java

CONDEC-834: Add more types of code files into the knowledge graph

---

src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/GitClient.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/RationaleFromCodeCommentExtractor.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/CommitMessageToCommentTranscriber.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/GitClientForSingleRepository.java
src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/versioncontrol/GitCommitMessageExtractor.java
src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/FilterSettings.java
src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/FilteringManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/DocumentationLocation.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/KnowledgeElement.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/Origin.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/PartOfJiraIssueText.java
src/main/java/de/uhd/ifi/se/decision/management/jira/model/git/ChangedFile.java
src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/KnowledgePersistenceManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/singlelocations/CodeClassPersistenceManager.java
src/main/java/de/uhd/ifi/se/decision/management/jira/quality/generalmetrics/CharacterizedJiraIssue.java
src/main/java/de/uhd/ifi/se/decision/management/jira/quality/generalmetrics/GeneralMetricCalculator.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ConfigRest.java
src/main/resources/js/condec.git.code.elements.linker.js
src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/commitmessagetocommenttranscriber/TestGenerateCommentString.java
src/test/java/de/uhd/ifi/se/decision/management/jira/filtering/TestFilterSettings.java
src/test/java/de/uhd/ifi/se/decision/management/jira/model/TestDocumentationLocation.java
src/test/java/de/uhd/ifi/se/decision/management/jira/model/TestOrigin.java
src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/decisiongroupmanager/TestGetGroups.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/configrest/TestPostSquashedCommits.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/viewrest/TestGetFilterSettings.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/dashboard/TestConDecDashboardItem.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/dashboard/TestFeatureBranchQualityDashboardItem.java
src/test/java/de/uhd/ifi/se/decision/management/jira/view/diffviewer/TestBranchDiff.java

* Fix that repo uri was incorrect in transcribed commits into Jira issue comments

CONDEC-838: Add origin attribute to KnowledgeElements to indicate the origin of commit elements

---

.travis.yml
src/main/resources/js/condec.decision.table.js
src/main/resources/js/nudging/condec.prompts.js
src/main/resources/js/recommendation/condec.decision.guidance.api.js
src/main/resources/js/recommendation/condec.decision.guidance.js
src/main/resources/templates/jiraIssueModule.vm
src/main/resources/templates/tabs/decisionGuidance.vm
src/main/resources/templates/tabs/decisionGuidanceTable.vm
src/main/resources/templates/tabs/decisiontable/view.vm

In this PR, the decision guidance feature is separated from the decision table, and each gets its own tab

CONDEC-958: Create a separate decision guidance tab

---

README.md
src/main/java/de/uhd/ifi/se/decision/management/jira/model/KnowledgeGraph.java
src/main/resources/js/condec.knowledge.page.js
src/main/resources/js/condec.rationale.backlog.js
src/main/resources/templates/filter/allCriteria.vm

…rationale backlog (subgraph details)

CONDEC-971: Fix that graph filtering leads to unpredictable results in rationale backlog

---

src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/FilterSettings.java
src/main/java/de/uhd/ifi/se/decision/management/jira/recommendation/Recommendation.java
src/main/resources/js/condec.api.js
src/main/resources/js/recommendation/condec.link.recommendation.js
src/test/java/de/uhd/ifi/se/decision/management/jira/filtering/TestFilterSettings.java
src/test/java/de/uhd/ifi/se/decision/management/jira/recommendation/TestRecommendation.java

* Ensure that sorting of recommendations is descending by score

CONDEC-1006: Fix empty element dropdown in link recommendation view

---

README.md
doc/features/knowledge-export.md
src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/MarkdownCreator.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ReleaseNotesRest.java
src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ViewRest.java
src/main/resources/css/jstree.css
src/main/resources/js/condec.api.js
src/main/resources/js/condec.dialog.js
src/main/resources/js/condec.export.js
src/main/resources/js/releasenotes/condec.release.notes.api.js
src/main/resources/templates/dialogs/exportDialog.vm
src/main/resources/templates/filter/allCriteria.vm
src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestMarkdownCreator.java
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/viewrest/TestGetMarkdown.java

The export functionality in markdown syntax should be used to add relevant decisions to the feature documentation in github.

CONDEC-1010: Enable to export knowledge subgraph as markdown text

---

src/main/java/de/uhd/ifi/se/decision/management/jira/rest/DecisionGuidanceRest.java
src/main/resources/js/recommendation/condec.decision.guidance.api.js
src/test/java/de/uhd/ifi/se/decision/management/jira/rest/decisionguidancerest/TestGetRecommendations.java

Accepted recommendations are not yet considered, this will be solved together with [CONDEC-991](https://jira-se.ifi.uni-heidelberg.de/browse/CONDEC-991)

CONDEC-992: Implement enforcement of the limit of listed recommendations in decision guidance
