cures-hub/cures-condec-jira

- src/main/resources/js/condec.api.js
- src/main/resources/js/condec.context.menu.js
- src/main/resources/js/condec.observable.js
- src/main/resources/js/view.condec.issue.module.js
- src/main/resources/js/view.condec.knowledge.page.js
We use the observer pattern to notify the views in case of model changes in JS. We introduced the observable JS closure object that represents the subject where the views (=observers) subscribe themselves to get notified. 
This pull request makes it possible to subscribe views as observers. The "observers" array is iterated through in the notify() method and the updateView() method of the respective views/observers is called.
Currently, the ConDecIssueModule and ConDecKnowledgePage are subscribed to the observable/subject. We need to add the ConDecTabPanel and future views.
> ConDec-404: Enable JS views to subscribe/register as observers in observable

- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/DecXtractEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/connector/ViewConnector.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/model/impl/CommentImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/model/impl/SentenceImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/persistence/ActiveObjectsManager.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/persistence/DecisionKnowledgeInCommentEntity.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/view/DecisionKnowledgeReport.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/view/IssueTabPanelRenderer.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/GenericLinkManager.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ConfigRestImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/KnowledgeRest.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ViewRest.java
- src/main/resources/js/view.commentTab.toolbar-init.js
- src/main/resources/js/view.condec.tab.panel.js
- src/main/resources/js/view.report.js
- src/main/resources/templates/decisionKnowledgeReport.vm
- src/main/resources/templates/tabPanel.vm
- src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/persistence/TestActiveObjectsManager.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/view/TestIssueTabPanelRenderer.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/mocks/MockCommentManager.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/activeobjectstrategy/ActiveObjectStrategyTestSetUp.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/activeobjectstrategy/TestDeleteLink.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/activeobjectstrategy/TestGetElementsLinkedWith.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/webhook/TestWebhookContentProvider.java
Fixes problems of:
- Sentences not properly deleted on several points.
- DB's not properly validated due to wrong return type.
- Two nearby (to irrelevant set) sentences merge in a third AO entry and all exist together.
- Bad performance due to View connector building every time tab panel is called (maybe also notify?!?) 
- Duplicate sentences creation is now solved in view connector via proper lock. 
- Notification for outside comment change is now thrown by Event Listener, deletes sentences directly without checking unnecessary stuff. 
- Set to irrelevant elements on second graph level were "away", now they are back on first level
> ConDec-399: Fix problem that decision knowledge elements from issue comments are doubled 

- src/main/resources/templates/jiraIssueModule.vm
When the JIRA.trigger method is called, the #include("templates/dialog.vm") in the jiraIssueModule.vm is called again. Thus, the dialog is included twice and the id is not unique anymore.
> ConDec-437: Fix that dialog stays empty

- pom.xml
- src/main/resources/atlassian-plugin.xml
* apparently resolution of resource handlers during plugin build process is done based on the extension of the name attribute in atlassian-plugin.xml resource tags. Adding .js to the name solves the issue observed for AMPS version 8. Without this change the YUI compiler will not be used for the /js/jquery/jquery.js
* switched the project to use AMPS 8.0.1, which requires developers to have the appropriate atlassian SDK installed. See pom.xml
* com.atlassian.maven.plugins changed its artifactID with SDK 8
* also removed enableFastdev as it is not supported any more
> ConDec-483: fix resource build handler resolution for AMPS 8+

- pom.xml
- src/main/java/de/uhd/ifi/se/decision/management/jira/config/AbstractSettingsServlet.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/ClassificationManagerForJiraIssueComments.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/ClassificationTrainer.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/DecXtractEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/DecisionKnowledgeClassifier.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/impl/ClassificationTrainerImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/impl/DecisionKnowledgeClassifierImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/impl/GitClientImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/GraphFiltering.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/JiraSearchServiceHelper.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/model/impl/LinkImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/model/text/impl/PartOfJiraIssueTextImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/ActiveObjectPersistenceManager.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/JiraIssuePersistenceManager.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/JiraIssueTextPersistenceManager.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/quality/CommentMetricCalculator.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ConfigRest.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ViewRest.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/webhook/WebhookConnector.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/webhook/WebhookContentProvider.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/webhook/WebhookEventListener.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/gitclient/TestSetUpGit.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/jiraissuepersistencemanager/TestDeleteDecisionKnowledgeElement.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/jiraissuepersistencemanager/TestInsertDecisionKnowledgeElement.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/jiraissuepersistencemanager/TestUpdateDecisionKnowledgeElement.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/rest/knowledgerest/TestGetSummarizedCode.java
- Change version of slf4j from 1.6.6 to 1.7.25  …
- Change Sys.error and error messages to Logger outputs  …
- Change sys.error and info to logger.error and Info in Classi
- Change sys.error to Logger errors in GitClientImpl
- Add Logger as public variable and add logger outputs to t…  …
- Remove unused TODO
- Add Logger as public object to the decisisonknowledgeclas…  …
- Exchange e.stacktrace to logger.error
- Extend logger errors of GraphFiltering
- Change e.staktrace to logger.error in JiraSearchServiceHe…  …
- Add Logger to LinkImpl and extend staktrace
- Add Logger to PartOfJiraIsseuTextImpl and log error in co…  …
-Extend catch error message with the error message
- Extend JiraIssuePersistenceManager with logger outputs
- Extend catch log outputs in JiraIssueTextPersistenceManager …
> ConDec-499: Improve logging, remove system.out.println and system.err.println

- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/ConDecEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/DecXtractEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/SummarizationEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/WebhookEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/JiraIssueTextPersistenceManager.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/TestWebhookEventListener.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/decxtracteventlistener/TestEventCommentAdded.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/decxtracteventlistener/TestEventCommentDeleted.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/decxtracteventlistener/TestEventCommentEdited.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/decxtracteventlistener/TestEventDescriptionEdited.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/decxtracteventlistener/TestEventIssueDeleted.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/decxtracteventlistener/TestRegisterFunctions.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/decxtracteventlistener/TestSetUpEventListener.java
- Move all event listener (DecXtract, Webhook) in an own package eventlistener
- Add a super class that handles the event listener calls for DecXtract and the Webhook
-  Change test calls to the new ConDecEventListener class
> ConDec-507: Build a super class for the EventListener

- .travis.yml
- pom.xml
- src/test/java/de/uhd/ifi/se/decision/management/jira/mocks/MockComponentAccessor.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/mocks/MockUserManager.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/rest/viewrest/TestGetVis.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/view/vis/TestVisGraphEdge.java
This pull requests updates the version of the active objects library to the latest version 3.1.6 and removes unneccessary dependencies with old versions such as guava from the pom.xml.
> ConDec-522: Update the version of the active objects library to the latest version 3.1.6

- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/KnowledgeRest.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/rest/knowledgerest/TestCreateDecisionKnowledgeElement.java
[issue] How to enable an external user (e.g. in Slack) to add a comment to an existing Jira issue containing decision knowledge? [/issue]
[decision] Add parameter keyOfExistingElement to createDecisionKnowledgeElement REST method of KnowledgeRest class! [/decision]
[alternative] Create new REST method! [/alternative]
[con] It is not clear for the user which method to use. [/con]
> ConDec-524: Add REST API method to create decision knowledge element in the comment of an existing JIRA issue using its key

- src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNote.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNoteConfiguration.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/ReleaseNoteIssueProposal.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TargetGroup.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TaskCriteriaPrioritisation.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/impl/ReleaseNoteConfigurationImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/impl/ReleaseNoteImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/releasenotes/impl/ReleaseNoteIssueProposalImpl.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestReleaseNote.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestReleaseNoteConfiguration.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestReleaseNoteIssueProposal.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestTargetGroup.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/releasenotes/TestTaskCriteriaPrioritisation.java
ConDec-558: add model classes and interfaces for:
- release note configuration
- issue proposal
- release notes
> ConDec-558: add release-note classes, enums and tests

- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/impl/GitClientImpl.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/gitclient/TestRemoveFeatureBranchNotPresentInRemote.java
* fixes in method GitClientImpl.java isPullNeeded method should contribute to CONDEC-586. This fix was needed for CONDEC-585 to work, therefore committed in same commit.
> ConDec-585: Delete locally branches deleted on remote

- src/main/java/de/uhd/ifi/se/decision/management/jira/model/KnowledgeType.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/model/impl/KnowledgeGraphImpl.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/KnowledgeRest.java
- src/main/resources/js/condec.api.js
- src/main/resources/js/condec.dialog.js
- src/test/java/de/uhd/ifi/se/decision/management/jira/rest/knowledgerest/TestCreateDecisionKnowledgeElement.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/view/treant/TestTreant.java
ich habe versucht in meine Jira Projekt SlacCondec ein Issue vom Typ Entscheidung (decision) mit einem Issue vom Typ Entscheidungsproblem (issue) zu verlinken, indem ich per Rechtsklick 'link existing decision knowledge element' ausgewählt habe.
Das hat aber leider nicht funktioniert. Es kam ein Error 500: 'Creation of Link failed'.
Scheinbar funktioniert das nur noch, wenn man neue Kommentare anlegt. Aber man kann keine Jira-Issues  mehr untereinander verlinken über dieses Menu?
Pro- und Con-Argumente werden in der Tree-View auch nicht mehr angezeigt?
> Condec 593: Bug create a link is no working

- README.md
- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/KnowledgeRest.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/impl/KnowledgeRestImpl.java
- src/main/resources/atlassian-plugin.xml
- src/main/resources/js/condec.api.js
This plug-in provides a [representational state transfer (REST) application programming interface (API)](https://github.com/cures-hub/cures-condec-jira/tree/master/src/main/java/de/uhd/ifi/se/decision/management/jira/rest) to retrieve, insert, update, and delete decision knowledge in Jira. 
The JIRA ConDec plug-in uses the REST services in the [REST Java Script client](https://github.com/cures-hub/cures-condec-jira/blob/master/src/main/resources/js/condec.api.js) from the user interface.
{issue}What path should the REST API have?{issue}
{alternative}The former path of the REST API of the ConDec Jira plug-in was: Jira base URL/rest/decisions/latest/decisions|config|view/REST service!{alternative}
{decision}The path of the REST API is: Jira base …
> CONDEC-619: Rename REST API path

- src/main/java/de/uhd/ifi/se/decision/management/jira/view/treeviewer/TreeViewer.java
- src/main/resources/js/condec.knowledge.page.js
- src/main/resources/js/condec.rationale.backlog.js
- src/main/resources/templates/filter/documentationDate.vm
Currently, the jstree viewer on the left side of the rationale backlog and overview pages only shows a list of knowledge elements. However, it used to show a list of trees.
In this work item, the jstree viewer is changed to show a list of trees as it used to.
{issue}Should the jstree viewer show a list of trees or only a list of single knowledge elements in the rationale backlog and overview?{issue}
{decision}Show a list of trees in the jstree viewer on the left side of the rationale backlog and overview!{decision}
{pro}Knowledge elements can be moved via drag & drop from on tree to another.{pro}
{con}Long loading times (16 seconds for all issues on the overview page).{con}
{alternative}Show a list of single knowledge elements in the jstree viewer on the left side of the rationale backlog …
> CONDEC-776: Show trees in jstree viewer instead of only a list of knowledge elements in the rationale backlog and overview

- src/main/java/de/uhd/ifi/se/decision/management/jira/ComponentGetter.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/ConDecEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/LinkEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/ProjectEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/implementation/JiraIssueTextExtractionEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/singlelocations/JiraIssueTextPersistenceManager.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/rest/ConfigRest.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/jiraissuetextextractioneventlistener/TestEventProjectDeleted.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/jiraissuetextextractioneventlistener/TestSetUpEventListener.java
Add ProjectEventListener interface and implement onProjectDeletion listener in JiraIssueTextPersistenceManager
[issue] How can we clean up after the deletion of a Jira project? [/issue]
[decision] Delete all knowledge elements and links from Jira issue description and comments after project deletion in database! Remove all singleton objects for the project! [/decision]
> CONDEC-848: Delete knowledge elements and links after project deletion

- .travis.yml
- pom.xml
- src/main/java/de/uhd/ifi/se/decision/management/jira/classification/implementation/ClassificationManagerForJiraIssueComments.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/ConDecEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/eventlistener/implementation/JiraIssueTextExtractionEventListener.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/extraction/parser/JiraIssueTextParser.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/model/KnowledgeType.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/model/PartOfJiraIssueText.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/persistence/singlelocations/JiraIssueTextPersistenceManager.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/view/macros/AbstractKnowledgeClassificationMacro.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/jiraissuetextextractioneventlistener/TestEventCommentAdded.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/jiraissuetextextractioneventlistener/TestEventCommentEdited.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/jiraissuetextextractioneventlistener/TestEventDescriptionEdited.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/jiraissuetextextractioneventlistener/TestReplaceIconsWithTags.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/eventlistener/jiraissuetextextractioneventlistener/TestSetUpEventListener.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/parser/TestCommitMessageParser.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/extraction/parser/TestJiraIssueTextParser.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/model/TestKnowledgeType.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/model/TestPartOfJiraIssueText.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/persistence/knowledgepersistencemanager/singlelocations/jiraissuetextpersistencemanager/TestDeleteElementsOfProject.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/view/macros/TestKnowledgeClassificationMacro.java
Change RenderMode of KnowledgeClassificationMacros to only render line breaks but nothing else (no inner macros, no text formatting) to be consistent with graph nodes
[issue] How should we deal with Jira issue text annotated with decision knowledge tags that includes text formatting, inner macros, images and so on? [/issue]
[decision] Do not render text formatting, inner macros, images and so on in knowledge classification macros, only render line breaks! [/decision]
[pro] Is consistent with the graph/tree nodes because there is also nothing rendered. [/pro]
[pro] A knowledge element should be formulated in a short easy way so that it is easy to understand without cluttering through images, macros and so on. All other information is context information, which a developer can read from the …
> CONDEC-809: Change RenderMode of KnowledgeClassificationMacros to only render line breaks

- src/main/resources/i18n/condec.properties
- src/main/resources/i18n/condec_de_DE.properties
- src/main/resources/js/classification/condec.text.classification.api.js
- src/main/resources/js/classification/condec.text.classification.js
- src/main/resources/js/nudging/condec.prompts.js
- src/main/resources/templates/jiraIssueModule.vm
- src/main/resources/templates/prompts/decisionGuidancePrompt.vm
- src/main/resources/templates/prompts/definitionOfDoneCheckingPrompt.vm
- src/main/resources/templates/prompts/linkRecommendationPrompt.vm
- src/main/resources/templates/prompts/nonValidatedElementsPrompt.vm
- src/main/resources/templates/prompts/unifiedPrompt.vm
In this PR, the unified prompt is updated so that it only has one button (continue).
> CONDEC-938: Improve the unified just-in-time prompt

- src/main/java/de/uhd/ifi/se/decision/management/jira/filtering/FilteringManager.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/model/KnowledgeElement.java
- src/main/java/de/uhd/ifi/se/decision/management/jira/model/KnowledgeGraph.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/filtering/filteringmanager/TestGetElementsMatchingFilterSettings.java
- src/test/java/de/uhd/ifi/se/decision/management/jira/filtering/filteringmanager/TestIsElementMatchingDocumentationCompletenessFilter.java
Use distance and predecessor to create mutable subgraph matching filter settings
> CONDEC-911: Try to speed-up graph filtering using jGraphT distanceAndPredecessor map without success

- src/main/java/de/uhd/ifi/se/decision/management/jira/recommendation/decisionguidance/KnowledgeSource.java
Fix [CONDEC-1018](https://jira-se.ifi.uni-heidelberg.de/browse/CONDEC-1018) by changing the `JsonIgnore` annotation from `import org.codehaus.jackson.annotate.JsonIgnoreProperties;` to `import com.fasterxml.jackson.annotation.JsonIgnoreProperties;`, which resolves the conflic with the `XmlElement` annotation, i.e. activates the serialization of the icon attribute, but keeps the deserialization deactivated.
> Condec 1018.fix.decision.guidance.recommendation.icons

- src/main/resources/js/recommendation/condec.decision.guidance.api.js
Delete cache when discarded recommendations are managed, so they are reloaded with their correct status when 'Recommend solution options' is clicked
> CONDEC-1022: Fix bug discard status not updated after manage discard

- src/main/java/de/uhd/ifi/se/decision/management/jira/recommendation/decisionguidance/ElementRecommendation.java
- src/main/resources/js/recommendation/condec.decision.guidance.api.js
- src/main/resources/js/recommendation/condec.decision.guidance.js
As recommendations are discarded by their text contents, i.e. summary, only (see [this decision](https://jira-se.ifi.uni-heidelberg.de/browse/CONDEC-990?focusedCommentId=108600&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-108600)), their arguments can be ignored. This resolves the deserialization issues causing the bug
> CONDEC-1023: Fix bug manage discard not possible with arguments
